name: Evaluate (Monthly)

on:
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

jobs:
  swe-bench-full:
    uses: ./.github/workflows/templates/eval-suite.yml
    with:
      suite: swe-bench-full
      python-version: "3.11"


